---
- name: Install Open Office rpms
# shell: yum localinstall -y {{item}}
  yum:
    name: "{{item}}"
    state: installed
    disable_gpg_check: yes
  with_items:
    - "{{open_office_installdir}}/{{open_office_rpms}}"
  when: custom_repo

- name: List OpenOffice packages installed    
  yum:
    list: OpenOffice
  register: openoffice_packages

- name: Display installed packages
  debug: msg="{{ openoffice_packages.split('\n') }}"  
