# main.yml - Install Python 3.4 from a repo
---
- name: Install Python36 packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python36
    - python36-setuptools
    - python36-devel

- name: Install pip
  easy_install:
    name: pip
    executable: easy_install-3.6
