---
install_r_packages: true

r_shiny_server_package: "https://download3.rstudio.org/centos6.3/x86_64/shiny-server-1.5.9.923-x86_64.rpm"
#r_shiny_server_package: "http://download3.rstudio.org/centos5.9/x86_64/shiny-server-1.5.3.838-rh5-x86_64.rpm"
r_shiny_server_package_state: "present"
