# main.yml - Install Python 2.7 and Packages from RedHat Satellite
---
- name: Install Python27 packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python27
    - python27-PyYAML
    - python27-python-setuptools
    - python27-python-devel
    - python27-python-libs
    - python27-python-pip
    - python27-python-psycopg2
    - python27-numpy
    - python27-scipy
    - python27-python-six
    - python27-python-tools
    - python27-tkinter
    - python27-python-virtualenv

#- name: Install pip
#  easy_install:
#    name: pip
#    executable: easy_install-3.6
